CC=mpicxx
CPPFLAGS = -g -O0 -W -Wall -pedantic -std=c++0x -I../libs
LDFLAGS = -lm
fisheye: fisheye.o ../libs/lspbmp.o ../libs/magnify.o

clean:
	rm -f fisheye fisheye.o ../lib/lspbmp.o ../libs/magnify.o
